component_depth: 1

exclude:
- /frontend/dashboard/plugins/.*
- /frontend/dashboard/documentation/.*
- /frontend/dashboard/build/.*
- /frontend/dashboard/dist/.*
- /frontend/dashboard/bower_components/.*
- /frontend/dashboard/Gruntfile\.js